CREATE TABLE Roles(
Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
RoleName NVARCHAR(50) NOT NULL
);

CREATE TABLE Users(
Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
Username VARCHAR(16) NOT NULL,
Password VARCHAR(16) NOT NULL,
FullName NVARCHAR(100) NOT NULL,
RoleId INT NOT NULL FOREIGN KEY REFERENCES Roles(Id)
);

CREATE TABLE Category(
Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
CategoryName NVARCHAR(50) NOT NULL
);

CREATE TABLE Tool(
Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
CategoryId INT NOT NULL FOREIGN KEY REFERENCES Category(Id),
ModelName NVARCHAR(100) NOT NULL,
OperatingSince DATE,
DecomissionedSince DATE,
SerialNumber NVARCHAR(100),
Notes NVARCHAR(255)
);